docs/nodes/overview.md

- Changed description of bridge node to specify that it bridges the block between the two networks
- Changed the references of "layers" to "networks" to so there's less confusion that the text is referring to networks within Celestia and not the entirety of Celestia.

Update overview descriptions

---

docs/nodes/bridge-validator-node.md

Pruning is needed so the database will still fit within the 100GB recommended disk size of the instructions. Currently with these configurations the Database will be around 25GB. Without this configuration it will grow beyond 200GB.

Add pruning instructions

---

docs/nodes/bridge-validator-node.md
docs/nodes/light-node.md

The path is already exported to `PATH` in a previous step

Avoid unecessary explicit path for binary already in PATH

---

docs/nodes/bridge-validator-node.md

I just noticed during the call recap that the SDD -> SSD typo is still there 😃

doc: fix typo

---

docs/developers/node-api.md
docs/nodes/bridge-node.md
docs/nodes/config-toml.md
docs/nodes/devnet-2.md
docs/nodes/light-node.md
docs/nodes/overview.md
docs/nodes/validator-node.md
sidebars.js

* Creates a separate `Devnet-2` Page with its own instructions on how validator and bridge nodes can connect to it.
* Creates an un-ordered list of options for network selection in Bridge and Validator tutorial guides.
* Splits Bridge-Validator tutorial into separate Bridge Node and Validator Node Tutorial
* Includes a config-toml guide from the networks repo for reference
* Adds code for how to always pull latest version from `celestia-app` and `celestia-node`

"Run A Node" Rearchitecture

---

docs/developers/wallet.md
docs/nodes/mamaki-testnet.md

These instructions avoid issues with wallets on current SDK version. Without this, users will get this error:
Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account not found: key not found

Instructions to use --keyring-backend=test

---

docs/developers/celestia-node.md

this is the output now for using the above command, some people check commit here it seems and use the older one which doesnt have the grpc flag in there yet

Bump celestia-node version

---

docs/nodes/light-node.md

This is a very weird bug where links in this doc: https://docs.celestia.org/nodes/light-node
get the `nodes` added in the url if you do the following:
1. Go to Light Node doc as linked above
2. Click on `here` under either dependencies or under Celestia Node
3. Now go back in the browser to Light Node page
4. Now do a refresh on the light node page
5. Click `here` again on either dependencies or Celestia Node
6. You will get a 404 because `developers` is added in the url

fix: broken link

---

docs/nodes/bridge-node.md
docs/nodes/config-toml.md
docs/nodes/consensus-full-node.md
docs/nodes/full-storage-node.md
docs/nodes/keys.md
docs/nodes/light-node.md
docs/nodes/mamaki-testnet.md
docs/nodes/overview.md
docs/nodes/systemd.md
docs/nodes/validator-node.md

I preserved capitalization for H1s where the noun was the sidebar name (ex. `Full Storage Node`, `Bridge Node`, etc.) and sentence cased all other titles (H2+).
Resolves https://github.com/celestiaorg/docs/issues/161

Sentence case titles

---

docs/nodes/validator-node.md

It is required to add the protocol to the `core.remote` flag else the error returned is `Error: cmd: while parsing 'core.remote': both protocol and host must present in the address`

Adding protocol to initialize bridge node

---

docs/developers/run-wordle.md

This way a developer will get an error when he tries to run it before changing the height.

Change the height to XXXXX

---

docs/concepts/how-celestia-works/data-availability-layer.md

`master` on celestia-core is deprecated. The default branch should be used instead. Related: https://github.com/celestiaorg/celestia-core/issues/830

Remove link to unmaintained celestia-core branch

---

docs/developers/run-wordle.md

The `-y` flag enables async submission and will error without `-y`

Add `-y` flag to submit-wordle command

---

docs/developers/celestia-node.mdx
docs/developers/node-tutorial.mdx
docs/nodes/light-node.mdx

On some macOS, users will sometimes encounter an error when running `make install`, the fix is to run `make go-install`
added to:

update macOS installation instructions for `celestia-node`

---

docs/developers/celestia-node.mdx

This is a PR to add commands to resolve error when a node needs to be reinitialized for Mamaki
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203328889144183

add error workaround for Mamaki

---

docs/developers/node-tutorial.mdx
docs/nodes/light-node.mdx

This PR adds installation commands for `cel-key` on the `nodes/light-node` page of Documentation. It also clarifies that creating keys uses the `cel-key` utility.
Generated from user feedback: `so I have found that you need to make cel-key (https://docs.celestia.org/nodes/keys/#installation) might be worth pointing to this in the Node setup part of the docs as it is not mentioned (https://docs.celestia.org/nodes/light-node/#install-celestia-node)`
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203328889144160

add clarification for `cel-key` utility on `nodes/light-node` 

---

docs/developers/docker.mdx
sidebars.js

This adds instructions to run Docker `celestia-node` containers.

add docker instructions for `celestia-node`

---

docs/developers/celestia-node-metrics.md
docs/developers/instantiate-testnet.md
docs/developers/node-tutorial.mdx
docs/nodes/light-node.mdx

I may have broken this (on the docs) when I [removed](https://github.com/celestiaorg/docs/pull/317/commits/f0f563aa5cafe705e0a485b9760e1a28b38e685b) these flags 😬 . just reverted changes in this PR

add back `--gateway` flags with no args

---

clean.sh
crowdin.yml
docusaurus.config.js

Removes zh language due to encoding issue, updates cleanup script to fix known encoding issues, and waiting on fixes from chinese community before retesting doc build with zh

Fix: Remove zh due to encoding bugs, update cleanup script

---

docs/concepts/how-celestia-works/data-availability-layer.md

I think the block size in bytes is misquoted in the docs, because k x k chunks = O(k^2) bytes

Fixing block size typo

---

docs/developers/node-tutorial.mdx
docs/nodes/bridge-node.mdx
docs/nodes/light-node.mdx

Removes an unnecessary port from older versions of `celestia-node`. There is a note in the docs for the port already, if the user uses a custom RPC, etc.

docs: remove unnecessary port on RPC URL

---

docs/developers/run-wordle.md

This fixes a mistake in key name in commands for the Wordle tutorial. Previously, it had `recipes-key` but needs to be `wordle-key` to match the `init.sh` script.

docs: update wordle-key from recipe-key to match init.sh

---

docs/developers/celestia-node-key.mdx
docs/developers/node-tutorial.mdx
docs/nodes/bridge-node.mdx
docs/nodes/full-storage-node.mdx
docs/nodes/light-node.mdx

This PR changes a few commands to use `arabica-2` when wanting to run against arabica using `0.6.1`, commands include:
- init command
- key generation command
- start command

update: fix p2p network label for 0.6.1 arabica

---

docs/nodes/consensus-full-node.md

Consensus Full Node docs reference non-existent files and settings in the `config.toml` file.
- The docs reference https://raw.githubusercontent.com/celestiaorg/networks/master/mocha/bootstrap-peers.txt which has changed to https://raw.githubusercontent.com/celestiaorg/networks/master/mocha/peers.txt
- The docs reference `bootstrap-peers` in the `.celestia-app/config/config.toml` file where there is no such configuration. Changing this to `persistent_peers` works.
These changes make it easier for a user to set up a Consensus Full Node and avoid getting stuck.

chore(docs): use persistent_keys config for consensus full node

---

docs/developers/node-tutorial.mdx
docs/nodes/celestia-node.mdx
docs/nodes/docker-images.mdx
docs/nodes/light-node.mdx

This upgrades Mocha to v0.6.3, Stable Mocha: https://github.com/celestiaorg/celestia-node/releases/tag/v0.6.3

deps: version bump to 0.6.3 for mocha

---

docs/developers/celestia-node-key.mdx

User was confused what the difference in `cel-key` and `celestia-appd` was. It is because there was a `celestia-app` command in the [guide](https://docs.celestia.org/developers/celestia-node-key/#steps-for-exporting-node-keys) for `celestia-node`. It's removed in this PR. 
Closes https://github.com/celestiaorg/docs/issues/455

Remove incorrect command from celestia-node wallet page

---

docs/developers/integrate-celestia.md

This changes the Celesita block time from 30 seconds to 15 seconds on the Integration page.

change Celestia blocktime to 15s

---

docs/nodes/validator-node.md

Under the [delegate stake section](https://docs.celestia.org/nodes/validator-node/#delegate-stake-to-a-validator)
It asks you to setup an env variable for your key as such:
```
VALIDATOR_WALLET=<validator-address>
```
The following step asks to run the following command to output the wallet address:
```
celestia-appd keys show $VALIDATOR_WALLET --bech val -a
```
The error is that the env variable should be example within `<>` should be `<validator-key-name>` and not `<validator-address>`. Otherwise you would receive the following error:
```
Error: <validator-address> is not a valid name or address: invalid Bech32 prefix; expected celestia, got celestiavaloper
```

update variable name

---

docs/developers/node-tutorial.mdx
docs/developers/rpc-tutorial.mdx
sidebars.js

- swaps RPC/Gateway tutorials because they were in wrong place
- switches order of `1. docs 2. tutorial` to `1. tutorial 2. docs`

Fix tutorial order and menu

---

docs/nodes/celestia-node.mdx

Motivation in Slack: https://celestia-team.slack.com/archives/C02F3DUTKEK/p1682010569663719?thread_ts=1682010228.564529&cid=C02F3DUTKEK
The changes that aren't for the new section were caused by my editor automatically applying Markdownlint. We may want to enable a CI linter on this repo to auto-format `.mdx` files

docs: troubleshooting section for headers

---

docs/developers/full-stack-modular-development-guide.md

The documentation tells the reader to create a deployment script named `Contracts.s.sol` however later deployment commands refer to `Contract.s.sol` resulting in a failed deployment.

Simple typo correction

---

docs/nodes/blockspace-race.mdx

This PR adds the Neuler RPC endpoint to the blockspace race doc page.

added Neuler RPC node

---

docs/developers/keplr.mdx
docs/developers/node-tutorial.mdx
docs/developers/prompt-scavenger.mdx
docs/nodes/celestia-app.mdx
docs/nodes/celestia-node.mdx
docs/nodes/environment.mdx
docs/nodes/light-node.mdx
docs/nodes/qgb-binary.mdx

This PR removes extra spaces from code blocks from adding variables. I added an extra space before the `<br />` which resulted in an extra space showing up in the code blocks.

docs: remove extra spaces from code blocks from variables

---

docs/developers/node-tutorial.mdx
docs/nodes/celestia-node.mdx
docs/nodes/environment.mdx
docs/nodes/light-node.mdx
versions/constants.js

This PR adds another variable to track go versions between different networks.
It replaces `golangNodeOther` with `golangNodeArabica` and uses `golangNodeMocha` for Mocha versions.

docs: add Go variable for Arabica and for Mocha

---

.github/workflows/deploy.yml
.github/workflows/preview.yml
.github/workflows/test-deploy.yml
docusaurus.config.js

This reverts commit 91471b0f242d7b40e481afdfca91dc5284d72ad0.
Using the public key as a secret is proving to create a blocker for contributing to docs, so reverting until we have a better path forward.
Potential solution: look into if algolia has a developer mode
```Shell
[INFO] Starting the development server...
[ERROR] ValidationError: "algolia.apiKey" is required
```

Revert "feat: add algolia API key as secret (#778)"

---

docs/developers/celestia-node-key.mdx
docs/developers/node-tutorial.mdx
docs/developers/prompt-scavenger.mdx
docs/nodes/celestia-node-metrics.md
docs/nodes/celestia-node-troubleshooting.mdx
docs/nodes/docker-images.mdx
docs/nodes/light-node.mdx

This is meant to be merged once Mocha and Arabica are upgraded. 
This PR adds the `--gateway.deprecated-endpoints` flag in alignment with https://github.com/celestiaorg/celestia-node/pull/2360. This is meant to not break existing functionality for developers or users, including Rollkit tutorials which I have opened an issue for https://github.com/rollkit/docs/issues/189. I also opened an issue on docs to https://github.com/celestiaorg/docs/issues/850 follow up with guidance on the deprecation
Resolves #849

deps: add gateway deprecated flag

---

versions/mocha_versions.js

Bump version for mocha-3 to node v0.11.0-rc7

bump version for node to rc7

---

docs/developers/celestia-app-vesting.md
docs/developers/optimism.mdx
docs/nodes/itn-pfb-transaction.md

Hey :wave:,
This PR will fix :
2 typos in `docs/developers/celestia-app-vesting.md`
1 typo in `docs/developers/optimism.mdx`
1 typo in `docs/nodes/itn-pfb-transaction.md`
Best!

docs: fix typos

---

docs/nodes/light-node.mdx

Closes https://github.com/celestiaorg/docs/issues/910
It's possible these were intentionally left as placeholders in the keys and wallet section. If that's the case, the issue and PR can be closed as won't fix.

fix: populate `--core.ip` for keys and wallet section

---

docs/developers/node-tutorial.mdx

docs: remove methods from CLI tutorial that do not work currently

---

docs/developers/deploy-on-bubs.md

The faucet is set up to be used on https://bubstestnet.com, but there is a link in the documentation to https://bubsfaucet.com, which does not work due to auth.

[bug] - resolve broken faucet link

---

docs/nodes/full-consensus-node.mdx

note: after this is implemented, i plan to complete #556
Resolves #522

chore: resolve inaccuracies around exposing consensus node's RPC

---

README.md
docs/nodes/full-storage-node.mdx

Issue #1073 was made to remove instances of "click here" in the documentation. #1093 resolved this issue, but I missed a few instances of this and noticed when I was[ updating the QGB source](https://github.com/celestiaorg/orchestrator-relayer/pull/511) with the same rule.
Note: a follow-up PR will be made to bring in changes from QGB source. This is why there are still instances of [here] in `qgb-*.md` pages on this branch and main.

fix: missed "no click heres"

---

docs/nodes/celestia-node-custom-networks.md
docs/nodes/celestia-node-metrics.md
sidebars.js

chore: Node Docs Updates

---

docs/developers/node-tutorial.mdx
docs/nodes/light-node.mdx

Adds missing `--p2p.network string` flags where they are missing, ahead of mainnet and #1138.

chore: add missing --p2p.network flags

---

docs/developers/blobstream-offchain.md
docs/developers/blobstream-rollup-outline.md

This PR adds an outline for how get started with a blobstream rollup by outlining the structure of a go implementation.

docs: add outline for how to make a blostream rollup

---

.vitepress/config.ts
developers/blobstream.md

Adds a missing page from migration.

chore: add missing page

---

nodes/celestia-app.md
public/celestia-app.sh

Resolves #1134
Resolves #1201
adding a prebuilt binary script to documentation for celestia-app, to allow users to download the binary instead of building it on their own.
```bash
curl -L -s https://docs.celestia.org/celestia-app.sh | bash
```

feat: add celestia-app prebuilt binary script

---

nodes/docker-images.md

This PR provides some information necessary for Windows users to be able to successfully run a persistent docker node. NTFS does not support linux style permissions so when a docker node is started the first time it creates the desired files to store the node, but afterwards will refuse to run indicating that the file containing the keys has permissions of 777 instead of 600. In order to avoid these issues it is recommended that Windows users install and run WSL and then run the docker container with the celestia node storage mounted within the WSL filesystem which obviously supports linux permissions.
Associated issue can be found here #1228 .

Persistent Docker Node Instructions for Windows Users

---

developers/how-to-stake-tia.md
nodes/docker-images.md

Resolves #1228
[running with persistent storage logs](https://app.warp.dev/block/qXtesjeJ8kLiWfS3FVDahN)

fix: fix docker start command

---

nodes/blobstream-orchestrator.md
nodes/consensus-node.md

Docs update following https://github.com/celestiaorg/orchestrator-relayer/pull/626

feat: orch update, mark orchestrator as required for validators

---

developers/eth-fallback.md

This PR updates the `eth-fallback` page OP stack section to reflect the changes in the `v1.0.0` release of OP stack integration.

eth-fallback: rewrite for release-v1.0.0

---

developers/optimism.md

Minor fixes to OP stack deployment guide. The port `26650` is required and should be retained. Also fixes network flag and node store location.

op stack: fix deploy guide

---

developers/optimism.md

Generalizes the `--core.ip string` flag to use `<rpc-url>` instead of a hardcoded endpoint that was for mainnet.

feat: generalize rpc flag

---

nodes/hardfork-process.md

This section seems no longer necessary considering Blockspace Race is over.

docs: remove Blockspace Race section

---

developers/blobstream.md
developers/ethereum-fallback.md
developers/optimism.md
nodes/blobstream-orchestrator.md
nodes/blobstream-relayer.md

While working on a different PR, the commit pre-hook failed because `yarn lint` resulted in a diff. Since these changes are unrelated to my PR, I included them here. 
Note: I wonder why CI lint didn't catch these? Do we want an issue to investigate the discrepancy between local lint and CI lint?

chore: run yarn lint

---

nodes/blobstream-bootstrapper.md
nodes/blobstream-orchestrator.md

Matches https://github.com/celestiaorg/orchestrator-relayer/pull/617

feat: match https://github.com/celestiaorg/orchestrator-relayer/pull/617

---

developers/submit-data.md

Variables are not accurate, based on governance params.
| Currently | Should be |
| --------- | ---------- |
| `GasCostPerBlobByte` | `blob.GasPerBlobByte` |
| `GasCostPerTransactionByte ` | `auth.TxSizeCostPerByte` |
Edit documentation to match `blob.GasPerBlobByte` and `auth.TxSizeCostPerByte` to be more accurate.

feat: add direct links to gov params for `blob.GasPerBlobByte` and `auth.TxSizeCostPerByte`

---

.github/workflows/deploy.yml

feat: remove keep_files=true

---

nodes/mocha-testnet.md

because the original endpoints worked. new one does not

fix: revert #1438 Update mocha-testnet.md

---

.vitepress/constants/arabica_versions.js

they are the same commit. the automation picked up the rc instead of release. the rc had no issues, which is why release is the same commit.

fix: use v1.7.0 instead of rc

---

.vitepress/constants/mocha_versions.js

Mocha is upgrading to celestia-node v0.15.0 today. The app version is based on celestia-node's `go.mod`. The core version is based on celestia-app's `go.mod`.

docs: mocha node v0.15.0

---

nodes/consensus-node.md
nodes/hardfork-process.md
nodes/validator-node.md

Add the v2 upgrade height for Mocha. Tagging @tty47 for awareness.
This value was derived using the `blockheight` tool from [celestia-app/tools](https://github.com/celestiaorg/celestia-app/tree/main/tools) with a 12.03 second blocktime based on [Mintscan](https://www.mintscan.io/celestia-testnet/)
```shell
$ go run main.go https://celestia-mocha-rpc.publicnode.com:443 2024-08-21T14:00:00
chainID: mocha-4
currentHeight: 2528740
currentTime: 2024-08-20 17:53:30.162475958 +0000 UTC
targetHeight: 2534757
targetTime: 2024-08-21 14:00:00 +0000 UTC
diffInSeconds: 72389
diffInBlockHeight: 6017
```

docs: mocha upgrade height

---

nodes/consensus-node.md
nodes/hardfork-process.md
nodes/validator-node.md

Follow up to https://github.com/celestiaorg/docs/pull/1672 the upgrade should happen on August 28th not August 21st. New height is based on:
```shell
$ go run main.go https://celestia-mocha-rpc.publicnode.com:443 2024-08-28T14:00:00
chainID: mocha-4
currentHeight: 2528880
currentTime: 2024-08-20 18:21:39.920330922 +0000 UTC
targetHeight: 2585031
targetTime: 2024-08-28 14:00:00 +0000 UTC
diffInSeconds: 675500
diffInBlockHeight: 56151
```

fix: mocha upgrade height

---

nodes/consensus-node.md
nodes/hardfork-process.md
nodes/validator-node.md

I estimated this height using the blockheight tool from celestia-app repo. On mainnet the block time is **11.75 seconds**
```
$ go run main.go https://celestia-rpc.publicnode.com:443 2024-09-18T14:00:00
chainID: celestia
currentHeight: 2268730
currentTime: 2024-09-04 13:49:30.057435899 +0000 UTC
targetHeight: 2371728
targetTime: 2024-09-18 14:00:00 +0000 UTC
diffInSeconds: 1.210229e+06
diffInBlockHeight: 102998
```
Then we revised the estimate to a block height that is 5 blocks before a multiple of 1500 so that a state sync snapshot is created shortly after the upgrade.
```
$ go run main.go https://celestia-rpc.publicnode.com:443 2371495
chainID: celestia
currentHeight: 2269085
currentTime: 2024-09-04 14:58:54.478635553 +0000 UTC
diffInBlockHeight: 102410
diffInTime: 334h15m17.5s …
```

docs: v2 upgrade height for mainnet beta

---

developers/optimism.md

docs: remove dependency of roll-op because it is installed in op-plasma-celestia

---

.vitepress/config.ts
developers/node-tutorial.md
index.md
nodes/celestia-app-wallet.md
nodes/ibc-relayer.md

Updates to pretty link `https://discord.gg/celestiacommunity`

docs: discord link to https://discord.gg/celestiacommunity

---

how-to-guides/common-node-setup.md
how-to-guides/mainnet.md
how-to-guides/mocha-testnet.md
reference/network-endpoints.md

docs: remove dead core endpoints

---

how-to-guides/quick-start.md
tutorials/celestia-node-key.md

docs: cleanup 1912

---

public/celestia-app.sh

docs: make app script similar to node

---

how-to-guides/celestia-app.md
how-to-guides/consensus-node.md

Closes https://github.com/celestiaorg/docs/issues/2018
Ready for review but we don't need to merge it until we release celestia-app v4.0.0-arabica (expected Monday May 5)

docs: app v4

---

how-to-guides/mainnet.md

- Add NODERS endpoints to analytics and explorer sections
- Alphabetize listings for better discoverability

docs: add NODERS endpoints and alphabetize service listings

---

how-to-guides/network-upgrade-process.md

Estimate based on https://www.mintscan.io/celestia/block/6680339
```
$ celestia-appd query signal upgrade --node [https://rpc.lunaroasis.net:443](https://rpc.lunaroasis.net/)
An upgrade is pending to app version 4 at height 6680339.
```

docs: v4 activation height for Mainnet Beta

---

.vitepress/constants/arabica_versions.js
.vitepress/constants/mainnet_versions.js
.vitepress/constants/mocha_versions.js

Related to https://github.com/celestiaorg/docs/issues/2218

Update node versions to v0.25.3 in arabica, mainnet, and mocha constants

---

how-to-guides/feegrant-for-blobs.md
tutorials/node-tutorial.md

Resolves https://github.com/celestiaorg/celestia-app/issues/5162 for docs

docs: bump minfee

---

tutorials/integrate-celestia.md

https://github.com/celestiaorg/docs/blob/1ce4b22d9133de0e468b3994942883ef256b476f/tutorials/integrate-celestia.md#L71
Since 5c630b4f42b86b74d1271ec8eecec78291ea037f & #2052 this section makes no sense. The pre-[Ginger](https://blog.celestia.org/ginger/) block time of 12s was very unusual, but 6s is an extremely common block time - e.g. used by Cosmos Hub.

delete paragraph about long block times

---

.vitepress/components/NetworkScriptLinks.vue
.vitepress/theme/index.ts
how-to-guides/consensus-node.md

feat: add versions to links to quick start scripts

---

how-to-guides/network-upgrade-process.md

```
celestia@validator-1:/root$ celestia-appd query signal upgrade
An upgrade is pending to app version 6 at height 8236886.
```

docs: mocha v6 upgrade height

---

.vitepress/constants/mainnet_versions.js

chore: update mainnet beta to celestia-node v0.26.4

---

how-to-guides/celestia-node-trusted-hash.md
how-to-guides/quick-start.md

feat: update docs for v0.26.x celestia-node
