- docs/nodes/bridge-validator-node.md
I've started a snapshot service that creates a new snapshot of the blockchain every day -> https://snaps.qubelabs.io/ 
I've also updated the documentation to include instructions on how to(optionally) start the network with a snapshot.
This should be a big improvement for new nodes joining because syncing from the beginning can take several hours/days, but with a pruned snapshot you can be synchronized in a matter of minutes.
> doc: Add quick-sync snapshot / bridge systemd

- docs/nodes/bridge-validator-node.md
- docs/nodes/light-node.md
Resolves this ticket: https://github.com/celestiaorg/docs/issues/42
> Yaz.update bandwidth requirement

- docs/nodes/devops-resources.md
- sidebars.js
Hi @jbowen93 please review this PR
> doc: Add docker-compose resources

- docs/community/calendar.md
- docs/community/coc.md
- docs/community/overview.md
- docusaurus.config.js
- sidebars.js
Code of Conduct, community calendar and community section.
> Community Resources and CoC

- .github/workflows/lint.yml
To merge into #67. I'll let @YazzyYaz fix the linting errors in that PR after this is merged.
> Add lint CI.

- package-lock.json
- package.json
> Upgrade Docusaurus

- docs/developers/celestia-app.md
- docs/developers/celestia-node.md
- docs/developers/environment.md
- docs/developers/wallet.md
- sidebars.js
Wanted to split out a lot of repetitive steps into their own pages and sections. Once this is approved and merged, I will make a new PR to link existing and new PRs to those sections after merging `main` into those branches.
> Rearchitect Developer Section

- docs/nodes/devnet-2.md
- docs/nodes/full-node.md
- docs/nodes/overview.md
- sidebars.js
Closes this https://github.com/celestiaorg/docs/issues/85
> Add Full Node Tutorial

- docs/nodes/mamaki-testnet.md
remove persistent peers from the manual.
> remove persistent peers

- docs/nodes/mamaki-testnet.md
- new rpc provider for mamaki testnet
> adding new rpc for mamaki

- docusaurus.config.js
Resolves https://github.com/celestiaorg/docs/issues/123
> Fix Broken Edit Link

- docs/developers/node-tutorial.md
- docs/nodes/bridge-node.md
- docs/nodes/full-storage-node.md
- docs/nodes/light-node.md
- docs/nodes/systemd.md
- docs/nodes/validator-node.md
To merge when https://github.com/celestiaorg/celestia-node/pull/768 is merged
> Add http prefix

- docs/developers/celestia-app.md
- docs/developers/celestia-node.md
- docs/developers/node-api.md
- docs/developers/node-tutorial.md
- docs/nodes/bridge-node.md
- docs/nodes/consensus-full-node.md
- docs/nodes/full-storage-node.md
- docs/nodes/light-node.md
- docs/nodes/mamaki-testnet.md
- docs/nodes/overview.md
- docs/nodes/validator-node.md
* Fixes based on this doc https://docusaurus.io/docs/markdown-features/links
> More Link Fixes

- docusaurus.config.js
Closes https://github.com/celestiaorg/docs/issues/63
> Add Algolia Search Bar

- docs/developers/celestia-node.md
Updated instructions to include new release candidate
> Bumped release candidate

- docs/developers/cosmwasm-contract-deployment.md
- docs/developers/cosmwasm-contract-interaction.md
- docs/developers/cosmwasm-dependency.md
- docs/developers/cosmwasm-environment.md
- docs/developers/cosmwasm.md
- sidebars.js
> Minor fixes for cosmwasm tutorial

- docs/developers/wallet.md
Motivation: https://changelog.com/posts/use-long-flags-when-scripting
> Prefer full command name in documentation

- docs/developers/instantiate-testnet.md
The genesis file is located in `$HOME/.celestia-app/config/genesis.json`
> fix: location of genesis file

- docs/developers/node-api.md
> doc: add docs for /namespaced_data

- docs/developers/wallet.md
Closes https://github.com/celestiaorg/docs/issues/170
> fix: celestia-appd start prior to query

- docs/nodes/mamaki-testnet.md
Closes https://github.com/celestiaorg/docs/issues/169
Because it's possible to get to these sections by following steps from the consensus full node guide (not just the validator guide)
> fix: remove backlinks

- docs/developers/node-tutorial.md
Closes https://github.com/celestiaorg/docs/issues/162
> docs: add troubleshooting section

- docs/community/translations.md
Hey, @YazzyYaz. 
Here is a first Guideline.
> Translations Guideline

- docs/developers/cosmwasm-contract-deployment.md
- docs/developers/cosmwasm-environment.md
> Change the height to XXXXX

- docs/concepts/specifications/reserved-namespace-id.md
- sidebars.js
Closes https://github.com/celestiaorg/docs/issues/59
> Add reserved namespace ids

- docs/developers/node-tutorial.md
Fixes broken link to RPC endpoints [here](https://docs.celestia.org/developers/node-tutorial/#connect-to-a-public-core-endpoint)
> Fixes broken link

- docs/developers/wordle-keeper.md
- docs/nodes/systemd.md
Hello @YazzyYaz 
Translators found 2 typos.
> Correcting typos

- docs/developers/celestia-node.md
v0.3.0 is now the latest release for celestia-node.
> Update celestia-node.md for v0.3.0

- docs/developers/celestia-node.md
> Revert "Update celestia-node.md for v0.3.0"

- docs/developers/integrate-celestia.md
- docs/developers/integrating-celestia.md
- sidebars.js
This is a PR to add an `Integrating Celestia` page to the Developer section of the Celestia docs.
> Add Integrating Celestia page to Developer section

- docs/nodes/light-node.md
Closes https://github.com/celestiaorg/docs/issues/226
> Add Mamaki Section to Light Node

- docs/developers/celestia-app-commands.md
Closes https://github.com/celestiaorg/docs/issues/239
Closes https://github.com/celestiaorg/docs/issues/236
Closes https://github.com/celestiaorg/docs/issues/234
Closes https://github.com/celestiaorg/docs/issues/233
Closes https://github.com/celestiaorg/docs/issues/232
> Add more celestia-app commands

- docs/developers/celestia-node.md
Closes https://github.com/celestiaorg/docs/issues/242
> Add node network selection

- docs/developers/environment.md
Changing the output of go version.
> Go version fix

- docs/developers/celestia-node-metrics.md
- i18n/fr/docusaurus-plugin-content-docs/current/developers/celestia-node-metrics.md
- i18n/zh/docusaurus-plugin-content-docs/current/developers/celestia-node-metrics.md
- sidebars.js
Closes https://github.com/celestiaorg/docs/issues/230
> Add Celestia Node Metrics section

- docs/developers/node-tutorial.md
Add code responses link to learn more about statuses
> doc: increase gas from 60k to 70k in pfd example

- docs/developers/cosmwasm-resources.md
Miscellanious should be Miscellaneous.
> Fixing Typo 

- docs/developers/environment.mdx
- docs/developers/node-tutorial.mdx
- docs/nodes/light-node.mdx
- i18n/fr/docusaurus-plugin-content-docs/current/developers/environment.mdx
- i18n/fr/docusaurus-plugin-content-docs/current/developers/node-tutorial.mdx
- i18n/fr/docusaurus-plugin-content-docs/current/nodes/light-node.mdx
- i18n/zh/docusaurus-plugin-content-docs/current/developers/environment.mdx
- i18n/zh/docusaurus-plugin-content-docs/current/developers/node-tutorial.mdx
- i18n/zh/docusaurus-plugin-content-docs/current/nodes/light-node.mdx
https://user-images.githubusercontent.com/46639943/197279897-3b218ed6-2786-4155-bba8-ee6f2ccff457.mp4
> Add Network and OS selection across docs

- docs/developers/celestia-app.mdx
- docs/developers/celestia-node.mdx
- docs/developers/cosmwasm-dependency.md
- docs/developers/gm-rollmint.md
- docs/developers/install-rollmint.md
- docs/developers/instantiate-testnet.md
- docs/nodes/consensus-full-node.md
- docs/nodes/validator-node.md
> tab versions for celestia-app, reinit light node instructions, update rollmint version

- docs/developers/node-tutorial.mdx
> remove duplicate commands

- docs/nodes/systemd.md
The previous ExecStart function was not working, Updated it.
> Update systemd light node command

- docs/developers/celestia-node.mdx
Quick fix for incorrect network selection flag.
> fix `--node.network` flag

- docs/developers/celestia-node.mdx
- docs/developers/gm-query.md
Hey ! 
Newtworks has been changed to Networks. 
From "You Rollup" to "Your Rollup".
> Fixing Typos

- sidebars.js
Resolves an issue in URLs from emojis being present in the sidebar.
> remove emoji from sidebars.js

- .github/workflows/deploy.yml
Resolving issues with PR preview
> Add keep_files to workflow

- docs/developers/celestia-app-commands.md
This is a PR to add links to description of keyring on `celestia-app-commands.md`. This helps the user understand what the mechanics of keyring are by linking to Cosmos and Go package documentation.
> add links to keyring on cosmos/go package

- docs/developers/ethermint.md
Altered the mention of 'Optimint' to 'Rollmint'.
> Update ethermint.md (change 'Optimint' to 'Rollmint')

- docs/community/translations.md
- docs/developers/build-modular.md
- docs/developers/deploy-solidity-ethermint-foundry.md
- docs/developers/ethermint-dependencies.md
- docs/developers/ethermint.md
- docs/nodes/hardfork-process.md
- docs/nodes/participate.md
Hey @YazzyYaz, hey @jcstein !
I'm adding sidebar_labels, and also, I modified the guideline about translations. 
Have a nice week!
> Adding Sidebar_labels and modifying Translation's Guideline

- docs/community/cohort-one-content.md
- docs/community/modular-fellows.md
- sidebars.js
This PR adds modular fellows cohort one content and calendar.
> add modular fellows content and calendar

- docs/nodes/full-storage-node.mdx
This PR moves `mdx-code-block` under the heading to fix the title.
> fix Heading on full storage node

- docs/developers/build-modular.md
> docs[fix]: broken link on build modular

- docs/developers/integrate-celestia.md
This adds a `Getting Started` section to the `Integrate Celestia` page. This page now aims to be a one-link solution to send to potential integration teams.
> docs: add recommended links to integration page

- docs/nodes/arabica-devnet.md
- docs/nodes/mamaki-testnet.md
> docs(typos): fix typos

- docs/concepts/how-celestia-works/transaction-lifecycle.md
This fixes the link breaking this action: https://github.com/celestiaorg/docs/actions/runs/3641449350/jobs/6147392410
Continued from https://github.com/celestiaorg/docs/pull/352.
> docs[fix]: broken link

- docs/developers/node-tutorial.mdx
- docs/nodes/docker-images.mdx
- docs/nodes/light-node.mdx
On my mac, localhost resulting in error:
```
Error: gateway: invalid listen address format: localhost
```
> docs[fix] - localhost -> 0.0.0.0

- docs/community/cohort-one-content.md
This PR updates the Modular Fellows Cohort One schedule.
> [chore]: update cohort one schedule

- docs/nodes/mocha-testnet.md
> docs: fix api and grpc links for Mocha

- docs/nodes/hardfork-process.md
> docs: Fix typo

- docs/nodes/docker-images.mdx
This PR resolves a merge conflict in `/docs/nodes/docker-images.mdx`
> docs: resolve conflict on docker image

- docs/community/cohort-one-content.md
This PR adds 3 new office hour sessions and edits the description for CosmWasm Lesson.
> docs: update mod fellow calendar

- docs/nodes/validator-node.md
Update validator-node tutorial to connect a validator to Mocha
> Update validator-node tutorial

- docs/nodes/systemd.md
> Updating systemctl comands with sudo

- docs/developers/node-tutorial.mdx
Arabica node instructions now include the `--p2p.network arabica` parameter, and the commit hash and build date for v0.6.0 is updated.
> node-tutorial: Update arabica instructions

- docs/developers/instantiate-ethermint.md
- docs/developers/node-tutorial.mdx
- docs/nodes/bridge-node.mdx
- docs/nodes/celestia-node-metrics.md
- docs/nodes/celestia-node.mdx
- docs/nodes/docker-images.mdx
- docs/nodes/full-storage-node.mdx
- docs/nodes/light-node.mdx
- docs/nodes/validator-node.md
This PR resolves:
- any missing `--p2p.network` flags
- small mistakes in existing commands
- updates `celestia-node` to v0.6.1 across docs https://github.com/celestiaorg/docs/pull/377/commits/b2ef6f67eb78d98c6bfa8b2bc3075c7599fb1ebe
> docs: mocha/arabica fixes from new node version

- docs/developers/cosmwasm-dependency.md
- docs/developers/cosmwasm-environment.md
- docs/developers/gm-query.md
- docs/developers/gm-rollmint.md
- docs/developers/install-rollmint.md
- docs/developers/instantiate-ethermint.md
- docs/developers/recipe-keeper.md
- docs/developers/recipe-message.md
- docs/developers/recipe-query.md
- docs/developers/recipe-rollup.md
- docs/developers/recipe-scaffold.md
- docs/developers/run-wordle.md
This PR updates new rollmint commands per guidance from @tzdybal https://github.com/celestiaorg/rollmint/issues/667#issuecomment-1360423279. This is paired with https://github.com/celestiaorg/devrel-tools/pull/7 and the following still need to be tested:
> docs: update rollkit commands

- docs/concepts/how-celestia-works/data-availability-layer.md
Closes https://github.com/celestiaorg/docs/issues/348
> fix: error in number of bytes

- docs/developers/instantiate-ethermint.md
- docs/developers/rollmint-on-ethermint.md
This PR modifies the setup for Ethermint so it is compatible with the most recent versions of `celestia-node`, `celestia-app`, and `rollkit`.
This PR allows:
https://user-images.githubusercontent.com/46639943/209009331-1cca20e1-5403-4147-863a-b42336de65eb.mp4
> docs: fix ethermint with new rollkit

- docs/developers/cosmwasm-environment.md
- docs/developers/gm-query.md
- docs/developers/instantiate-ethermint.md
- docs/developers/recipe-rollup.md
- docs/developers/run-wordle.md
This PR resolves the following errors in gm tutorial:
```sh
init.sh: line 11: md5sum: command not found
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  2459    0  2459    0     0   8379      0 --:--:-- --:--:-- --:--:--  8845
170599
Cosmos SDK's version is: stargate - v0.46.3
🛠  Building proto...
📦 Installing dependencies...
🛠  Building the blockchain...
cannot build app:
error while running command go build -o /Users/itamarreif/code/go/bin/gmd -mod readonly -ldflags -X github.com/cosmos/cosmos-sdk/version.Name=Gm -X github.com/cosmos/cosmos-sdk/version.AppName=gmd -X github.com/cosmos/cosmos-sdk/version.Version= -X github.com/cosmos/cosmos-sdk/version.Commit=f3a10ec0bf7c759822d3061aab43c798b1bff766 -X …
```
> docs: IAVL and md5sum edits for tutorials

- docs/developers/celestia-app-wallet.md
- docs/developers/node-tutorial.mdx
Docs refer only to arabica-faucet. Adding mocha-faucet here so readers can avoid getting stuck/waste time if they are working on setting up a mocha wallet/node/validator.
> chore: Add mocha-faucet to wallet and node tutorial pages

- docs/developers/full-stack-modular-development-guide.md
Removes a duplicate line in the example code for smart contract.
> docs: remove duplicate pragma solidity

- docs/developers/cosmwasm-contract-deployment.mdx
- docs/developers/cosmwasm-contract-interaction.md
- docs/developers/cosmwasm-dependency.md
Temporary fix for https://github.com/celestiaorg/rollmint/issues/680
> docs: fix cosmwasm rollmint version & update tutorial commands

- docs/developers/node-tutorial.mdx
- docs/nodes/consensus-full-node.md
- docs/nodes/light-node.mdx
> docs: change port to 127.0.0.1 for consistency across docs & scripts

- docs/developers/cosmwasm.md
- docs/developers/ethermint.md
- docs/developers/gm-world.md
- docs/developers/recipe-book.md
- docs/developers/wordle.md
This accompanies https://github.com/celestiaorg/devrel-tools/pull/8 and adds note to docs on tutorials for user to use Mocha, or manually modify if they decide to use Arabica.
> docs: add note about networks for tutorial scripts

- docs/developers/full-stack-modular-development-guide.md
Closes https://github.com/celestiaorg/docs/issues/386
> fix links in full stack tutorial

- .github/workflows/preview.yml
Adds back PR previews. [Tested with Rollkit docs](https://github.com/rollkit/docs/pull/45/commits/8f698d2404aaf74bec49c5f54fa73890830644de).
Rollkit Preview: https://rollkit.dev/pr-preview/pr-45/
Closes https://github.com/celestiaorg/docs/issues/424
> Set `keep_files: true` on `preview.yml`

- docs/nodes/arabica-devnet.md
This fixes the API endoint for Arabica.
> Update arabica API endpoint

- docs/nodes/devops-resources.md
Hello ! 
Just found one typo. Have a nice week !
> Fixing a Typo

- docs/nodes/mocha-testnet.md
Add counterpoint software Mocha RPC, API and gRPC endpoints to the documentation.
> Add counterpoint software Mocha endpoints

- .github/workflows/deploy.yml
- .github/workflows/preview.yml
> github: update deploy action to allow for previews and resets

- docs/developers/keplr.mdx
- docs/developers/node-tutorial.mdx
- docs/nodes/bridge-node.mdx
- docs/nodes/celestia-app.mdx
- docs/nodes/celestia-node-metrics.md
- docs/nodes/celestia-node.mdx
- docs/nodes/docker-images.mdx
- docs/nodes/environment.mdx
- docs/nodes/full-storage-node.mdx
- docs/nodes/light-node.mdx
- docs/nodes/systemd.md
- docs/nodes/validator-node.md
https://user-images.githubusercontent.com/46639943/215582668-baa04d18-5e54-46da-b5ee-0c6da1338d39.mp4
> Add construction sign (Arabica) and rearrange Mocha & Arabica

- docs/developers/cosmwasm-dependency.md
- docs/developers/gm-rollmint.md
- docs/developers/install-rollmint.md
- docs/developers/recipe-scaffold.md
- docs/developers/rollmint-on-ethermint.md
This is a PR to update the Rollkit installation commands on tutorials, until we launch Rollkit.
> change install rollkit commands (temporary)

- docs/developers/node-tutorial.mdx
- docs/nodes/celestia-node.mdx
- docs/nodes/docker-images.mdx
- docs/nodes/light-node.mdx
Bumps Mocha to `celestia-node v0.6.4`
> deps: version bump to 0.6.4 for Mocha

- docs/developers/node-api.md
> docs: Missing Backslash

- docs/concepts/data-availability-faq.md
- docs/developers/build-modular.md
- docs/developers/celestia-node-key.mdx
- docs/developers/cosmwasm.md
- docs/nodes/bridge-node.mdx
> Fix: typos

- docs/developers/keplr.mdx
- docs/developers/node-tutorial.mdx
- docs/nodes/celestia-node.mdx
- docs/nodes/docker-images.mdx
- docs/nodes/light-node.mdx
> Upgrade Arabica to v0.7.0-rc1

- docs/community/cohort-one-content.md
Closes https://github.com/celestiaorg/docs/issues/454
> Add Demo Day link to Community section

- versions/arabica_versions.js
> Update arabica version

- docs/nodes/docker-images.mdx
Closes https://github.com/celestiaorg/docs/issues/464
> Update docker image for mocha with sha, until release is tagged

- docs/nodes/local-devnet.md
- sidebars.js
This PR adds a guide on how to run a `local-celestia-devnet` and also a guide on how to create a Rollkit rollup that posts to that devnet.
I split this tutorial up across Rollkit and Celestia docs.
Linked to https://github.com/celestiaorg/devrel-tools/pull/9 and closes https://github.com/celestiaorg/docs/issues/438
> Add guide on `local-celestia-devnet`

- versions/arabica_versions.js
- versions/constants.js
> deps: bump arabica version & chain id

- docs/nodes/docker-images.mdx
> deps: remove slice on arabica docker images

- versions/arabica_versions.js
> bump node version for arabica

- docs/nodes/bridge-node.mdx
- docs/nodes/validator-node.md
> Update hardware requirements

- docs/developers/node-tutorial.mdx
- docs/nodes/full-storage-node.mdx
- docs/nodes/validator-node.md
This PR fixes local paths from a re-architecture of the docs linking to RPC endpoints for Mocha and Arabica.
> Fix outstanding broken links from doc re-architecture

- docs/developers/fuelmint.md
- sidebars.js
> Fuelmint docs

- docs/nodes/participate.md
> Fixing a typo : Update participate.md

- docs/developers/fuelmint.md
- docs/nodes/full-storage-node.mdx
- docs/nodes/light-node.mdx
> Remove old flag

- docs/developers/node-tutorial.mdx
- docs/nodes/celestia-node.mdx
- docs/nodes/light-node.mdx
faced some problems installing the node, fix it by adding "make build"
> Update install commands for Ubuntu(AMD)

- versions/arabica_versions.js
Bump Arabica version to 0.7.0-rc10
> deps: upgrade arabica versions

- docs/community/translations.md
- docs/nodes/mocha-testnet.md
> chore(typos): fix typos

- sidebars.js
As it only relates to using celestia-node bridge, light and full.
> node config.toml should be under celestia-node

- docs/nodes/participate.md
Furthermore, we might want to add links to the corresponding Discord pages so users can easily jump across
> Add blockspace race to the participate page

- docs/nodes/relayer.md
- sidebars.js
Closes: https://github.com/celestiaorg/docs/issues/510
> Add a page on relayers and IBC

- docs/community/cohort-one-content.md
During Translation on Crowdin, I found a typo which is I'm going to submit to avoid any confusion for translators.
Note:
Before Correction: 238 ### **Jan 9 - Week 16 - submissions bue**
After Correction: 238 ### **Jan 9 - Week 16 - submissions due**
> Fixing a typo: cohort-one-content.md

- docs/nodes/celestia-app-metrics.md
- sidebars.js
This PR adds a short walkthough to setting up Prometheus and Grafana to monitor your celestia instance
> Add a page on metrics for the consensus node

- docs/nodes/blockspace-race.md
> Add kjnodes public endpoints

- docs/nodes/blockspace-race.md
> Add WayneWayner Endpoints

- docs/nodes/blockspace-race.md
> add mzonder rpc, api, grpc

- docs/nodes/blockspace-race.md
> Add Ryabina.io RPC nodes for blockspacerace

- docs/nodes/blockspace-race.md
> Add Chainode Tech - RPC, gRPC and API Endpoints

- docusaurus.config.js
- package.json
- yarn.lock
Fixes: https://github.com/celestiaorg/docs/issues/486
The Latex equations in the documentation were not rendering. This PR adds the necessary imports to fix this. 
[This documentation](https://docusaurus.io/docs/2.2.0/markdown-features/math-equations) was used to fix the issue.
**OLD**: 
**NEW**:
> fix latex equation formatting

- docs/nodes/blockspace-race.md
> Add suntzu - RPC, gRPC and API Endpoints

- docs/nodes/celestia-node.mdx
> Update commands to reinit nodes

- docs/nodes/docker-images.mdx
> fix: wrong network in docker command

- docs/community/cohort-one-content.md
> Add project repos to MF calendar/content

- docs/nodes/itn-toolings.md
> fix: rollmint -> rollkit

- docs/developers/celestia-app-wallet.md
- docs/developers/celestia-node-key.mdx
- docs/developers/node-tutorial.mdx
- docs/developers/prompt-scavenger.mdx
- docs/developers/rpc-tutorial.mdx
- docs/nodes/bridge-node.mdx
- docs/nodes/celestia-node-metrics.md
- docs/nodes/celestia-node.mdx
- docs/nodes/consensus-full-node.md
- docs/nodes/docker-images.mdx
- docs/nodes/full-storage-node.mdx
- docs/nodes/instantiate-testnet.md
- docs/nodes/light-node.mdx
- docs/nodes/validator-node.md
> Add port section

- docs/nodes/full-storage-node.mdx
- docs/nodes/light-node.mdx
> fix: pfd -> pfb for mocha

- docs/nodes/celestia-node.mdx
This makes guidance more clear in the "Troubleshooting" section of Celestia node.
> docs: add callouts for clearing data store

- docs/nodes/blockspace-race.md
faucet amount update from 500 to 50
> Update blockspace-race.md - faucet amount

- sidebars.js
This puts docker first in the run a node section. This is because it is the easiest way to get started, and there is a note to go to the next pages if the user desires to run the binary.
This improves UX.
> docs: put docker first

- docs/nodes/systemd.md
> Update systemd path variable

- docs/nodes/blockspace-race.md
> Add Blockscope.net RPC to the list

- docs/nodes/blockspace-race.md
> Update blockspace race with BloClick RPC/gRPC/API

- docs/nodes/itn-pfb-ui.md
> Add links to pfb/retrieve data to ITN task

- docs/nodes/consensus-full-node.md
> Updated chain-id for blockspacerace

- docs/nodes/blockspace-race.md
> Update blockspace-race.md, RPC/gRPC/API - GPvalidator

- docs/developers/node-gateway-docs.mdx
Resolves https://github.com/celestiaorg/celestia-node/pull/1991
> chore: remove /transfer endpoint & add BSR tab for PFB

- docs/nodes/docker-images.mdx
> Add link to docker key management section

- docs/nodes/blockspace-race.md
> Forbole RPC node

- docs/nodes/celestia-app.mdx
- docs/nodes/celestia-node.mdx
> Add more details for ports on node/app

- docs/developers/rpc-tutorial.mdx
- docusaurus.config.js
> Add CLI docs

- docs/nodes/celestia-node.mdx
> Add upgrade your binary section

- docs/developers/rpc-tutorial.mdx
> fix: add directions for auth token

- docs/nodes/blockspace-race.mdx
- docs/nodes/itn-rpc-node.md
- docs/nodes/participate.md
- src/components/VersionTags.jsx
- versions/constants.js
> docs: add variables for BSR versions on BSR page

- docs/nodes/blockspace-race.mdx
> Add RPC/GRPC/API

- docs/nodes/blockspace-race.mdx
> Adding public rpc endpoint for spidey

- docs/nodes/docker-images.mdx
> docs: add section on docker persistent storage

- docs/community/cohort-one-content.md
> docs: update link and comment out broken link

- docs/nodes/blockspace-race.mdx
update rpc end point of citizen cosmos validator http://rpc.testnet.celestia.citizencosmos.space/
> update rpc end point of citizen cosmos validator

- docs/developers/rpc-tutorial.mdx
> docs: add more to rpc cli guide

- docs/nodes/celestia-node.mdx
> docs: add section on node store location & keys

- docs/nodes/blockspace-race.mdx
> Smrti Lab public rpc added

- docs/nodes/validator-node.md
> chore: reword the qgb setup keys to refer to only one key

- docs/nodes/blockspace-race.mdx
Add DSRV public RPC endpoint for community
> Add DSRV RPC endpoint

- docs/nodes/blockspace-race.mdx
Add our public endpoints in celestia-itn for bonus phase
```
some example)
$ curl https://rpc-celestia-itn.cosmostation.io/status
$ curl https://lcd-celestia-itn.cosmostation.io/cosmos/base/tendermint/v1beta1/node_info
$ grpcurl grpc-celestia-itn.cosmostation.io:443 list
```
> Add Cosmostation Public Endpoints in Blockspace-race

- docs/nodes/celestia-node.mdx
> add unsafe-reset-store docs for v0.9.0 and higher

- docs/nodes/blockspace-race.mdx
> add [NODERS]TEAM API, RPC, gRPC 

- docusaurus.config.js
Closes https://github.com/celestiaorg/docs/issues/649 and https://github.com/celestiaorg/docs/issues/626
> feat: remove locale select in navbar

- docs/nodes/blockspace-race.mdx
> docs: update P3 end time

- docs/nodes/celestia-node.mdx
> docs: update instructions for config remove + add tabs for these sections

- docs/developers/node-tutorial.mdx
- docs/developers/prompt-scavenger.mdx
- docs/nodes/celestia-node.mdx
- docs/nodes/light-node.mdx
- versions/constants.js
> Add variable for golang on bsr

- docs/developers/prompt-scavenger.mdx
- docs/nodes/environment.mdx
Missed a few variables on Friday in #658.
> fix: missing variables from #658

- docs/nodes/blockspace-race.mdx
Adding Figment's RPC, gRPC and API blockspacerace-0 endpoints.
> feat: adding figment's blockspacerace endpoints

- docs/nodes/blockspace-race.mdx
> Add RPC/gRPC/REST endpoints

- docs/nodes/blockspace-race.mdx
Adding the below endpoints:
```
RPC:
https://celestia-rpc.stakin-nodes.com:443
REST:
https://celestia-rest.stakin-nodes.com:443
gRPC:
celestia-grpc.stakin-nodes.com:443
```
> Add Stakin endpoints to blockspace-race.mdx

- versions/constants.js
Updates golang version for BSR to 1.20.2
> deps: update golangNodeBSR version

- docs/nodes/docker-images.mdx
This makes the commands for BSR mirror the commands for Arabica and Mocha, improving UX.
> fix: add RPC to docker run for BSR

- docs/nodes/blockspace-race.mdx
Add http://rpc.test.fcstech.de/
> Add FCS RPC endpoint

- docs/nodes/blockspace-race.mdx
> Add StakingCabin RPC, API, gRPC endpoints

- docs/nodes/blockspace-race.mdx
> Add public RPC endpoint (0xFury)

- docs/concepts/data-availability-faq.md
> docs: clarify FAQs for DA/storage

- docs/nodes/blockspace-race.mdx
> Validatus public services - blockspace-race.mdx

- docs/nodes/blockspace-race.mdx
> RPC from Brightlystake

- docs/nodes/blockspace-race.mdx
Add Upnode's RPC, gRPC and API endpoint for blockspacerace
> Add upnode public rpc endpoint

- docs/nodes/blockspace-race.mdx
> Add Aviaone's RPC and API

- docs/nodes/blockspace-race.mdx
Hi
Please find the addition of Staking4All endpoints for
- rpc
- api
- grpc
This is for the bonus phase challenges
> Added Staking4All ITN Submission for RPC

- docs/nodes/blockspace-race.mdx
> Collapse BSR endpoints to reduce clutter and fix broken links

- docs/nodes/blockspace-race.mdx
Add RPC/API endpoints for Node Guardians
> Node Guardians: Added RPC/API endpoints

- docs/developers/optimism.md
- sidebars.js
This replaces #490 to resolve build errors from outdated branch.
> add OP x Celestia doc

- docs/nodes/blockspace-race.mdx
Adding staker space endpoints to the list for the final phase.
adding a RPC, GRPC and API endpoint to the blockspacerace docs
> add staker space api endpoints

- docs/nodes/itn-hardfork-upgrade.md
> Update itn-hardfork-upgrade.md with correct HF block

- docs/nodes/itn-hardfork-upgrade.md
- docs/nodes/itn-qgb-setup.md
> Upgrade height change

- docs/nodes/blockspace-race.mdx
> Add FreshSTAKING RPC

- docs/nodes/blockspace-race.mdx
> Add avril14th.org RPC&API

- docs/nodes/qgb-binary.mdx
- versions/constants.js
> docs: add QGB version to installation instructions

- docs/nodes/blockspace-race.mdx
> Update blockspace-race.mdx BLOCLICK RPC

- docs/nodes/blockspace-race.mdx
> AviaOne's Grpc

- docs/nodes/blockspace-race.mdx
Add 01node Public RPC to the documentation
> Add 01node Public RPC

- docs/nodes/blockspace-race.mdx
> Add maplenodes RPC

- docs/nodes/blockspace-race.mdx
> Brightlystake endpoints and status monitoring tool

- docs/nodes/blockspace-race.mdx
This PR moves RPC websockets to the RPC section from #727
> fix: move websocket endpoints to correct section

- docs/nodes/blockspace-race.mdx
P2P.ORG RPC and gRPC endpoints added.
> P2P.ORG endpoints adding

- docs/nodes/blockspace-race.mdx
> Update end time

- docs/nodes/blockspace-race.mdx
Add RPC and gRPC node urls for Staking Facilities using the stakingwizard.com domain.
> Update blockspace-race.mdx for Staking Facilities Endpoints

- docs/nodes/blockspace-race.mdx
> Add RPC endpoint

- docs/nodes/blockspace-race.mdx
> Add Notional endpoints

- docs/nodes/blockspace-race.mdx
> Adding Gunter's RPC and API endpoints

- docs/nodes/blockspace-race.mdx
This pull request adds ZKValidator's RPC endpoint to the documentation of the Blockspace Race
> add zkvalidator rpc

- docs/nodes/full-storage-node.mdx
> add note on graceful restart

- docs/nodes/docker-images.mdx
This fixes an outdated example, and can be switched to Arabica/Mocha later on easily.
> docker: use variable for BSR version

- docs/nodes/docker-images.mdx
This clearly separates the "quick start" and "persistent storage" sections of Docker setup.
> docs: update docker to show 2 setups more clearly

- docs/developers/light-node-video.md
- docs/nodes/docker-images.mdx
- sidebars.js
Adds videos for beginners to run a light node.
> docs: add Running a Celestia light node for beginners tutorial

- docs/nodes/arabica-devnet.md
- sidebars.js
- versions/constants.js
This PR updates Arabica with the following:
Explorer :mag:
https://explorer-arabica-8.celestia-arabica.com/arabica-8
APIs :spider_web:
1317
https://api-arabica-8.consensus.celestia-arabica.com/
https://api-2-arabica-8.consensus.celestia-arabica.com/
TM REST RPC: 26657
https://rpc-arabica-8.consensus.celestia-arabica.com/
https://rpc-2-arabica-8.consensus.celestia-arabica.com/
TM GRPC: 443
grpc-arabica-8.consensus.celestia-arabica.com:443
grpc-2-arabica-8.consensus.celestia-arabica.com:443
Faucet :potable_water:
https://faucet-arabica-8.celestia-arabica.com/
> deps: update Arabica

- docs/developers/keplr.mdx
- docs/developers/node-tutorial.mdx
- docs/nodes/bridge-node.mdx
- docs/nodes/docker-images.mdx
- docs/nodes/light-node.mdx
Fixes example commands and Keplr page.
> docs: add missed updates for Arabica

- docs/developers/keplr.mdx
- docs/developers/node-tutorial.mdx
- docs/nodes/arabica-devnet.md
- docs/nodes/bridge-node.mdx
- docs/nodes/docker-images.mdx
- docs/nodes/light-node.mdx
This PR swaps `http://consensus-full-arabica-8.celestia-arabica.com/` for `https://rpc-arabica-8.consensus.celestia-arabica.com/ ` and removes `https://rpc-2-arabica-8.consensus.celestia-arabica.com/` as a secondary RPC endpoint.
> docs: swap RPC for Arabica

- docs/developers/intro-to-op-stack.md
- docs/developers/optimism-devnet.md
- docs/developers/optimism.mdx
> docs: change op stack from BSR to arabica

- versions/arabica_versions.js
> docs: upgrade Arabica node version from v0.11.0-rc1 to v0.11.0-rc2

- docs/developers/celestia-node-key.mdx
- docs/developers/node-tutorial.mdx
- docs/nodes/bridge-node.mdx
- docs/nodes/docker-images.mdx
- docs/nodes/light-node.mdx
- docs/nodes/mocha-testnet.md
Based on https://github.com/celestiaorg/celestia-node/pull/2277. Resolves reported "bugs" and errors encountered since this was added to v0.11.0-rc2 and v0.10.3 last week.
> docs: update start commands to remove http/https

- .github/workflows/deploy.yml
- .github/workflows/preview.yml
- .github/workflows/test-deploy.yml
- docusaurus.config.js
> feat: add algolia API key as secret

- versions/arabica_versions.js
> docs: hotfix, bump back to rc0 for app for arabica

- sidebars.js
> docs: add sov labs/dymension and alphabetize rollup menu

- docs/nodes/celestia-node.mdx
This removes outdated "Upgrade your binary" instructions.
> docs: edit upgrade binary section

- sidebars.js
> style: collapse OP section

- docs/nodes/arabica-devnet.md
- docs/nodes/blockspace-race.mdx
- docs/nodes/mocha-testnet.md
- docs/nodes/participate.md
- docusaurus.config.js
> docs: add network upgrade channel

- docs/developers/node-api.md
- sidebars.js
> docs: add node api page for category

- docs/developers/node-tutorial.mdx
> docs: improve node tut

- docs/developers/demos.md
- sidebars.js
> docs: add demos page

- docs/developers/node-tutorial.mdx
- docs/nodes/arabica-devnet.mdx
- docs/nodes/bridge-node.mdx
- docs/nodes/celestia-node-troubleshooting.mdx
- docs/nodes/docker-images.mdx
- docs/nodes/light-node.mdx
Resolves #833 on current version of arabica.
> fix: start commands for *current* version of arabica

- docs/developers/node-tutorial.mdx
> docs: add back balanceForAddress to RPC tut

- docs/developers/demos.md
> docs: fix link to github instead of dead demo

- docusaurus.config.js
Made sidebar totally collapsible
> sidebar-update

- docs/concepts/how-celestia-works/transaction-lifecycle.md
- docs/developers/node-tutorial.mdx
- docs/nodes/bridge-node.mdx
- docs/nodes/full-storage-node.mdx
- docs/nodes/itn-deploy-bridge.md
- docs/nodes/light-node.mdx
resolves #785 
This PR changes PFD to PFB ahead of a Mocha upgrade.
Note: this PR should be merged before #783 and #792, because this way there will be conflicts to resolve than if this PR were merged first.
> docs: PFD -> PFB ahead of mocha upgrade

- docs/nodes/validator-node.md
> docs: bump to mocha-3 in validator node

- sidebars.js
Page was not removed in order to not break backlinks
> docs: remove BSR from sidebar

- docs/nodes/participate.mdx
> docs: comment out version tags for BSR on networks page

- docs/nodes/full-consensus-node.md
- docs/nodes/validator-node.md
> bump celestia-app to mocha-3

- docs/developers/build-modular.md
Remove the wrong first sentence and add link to the CTA in the intro.
> Update build modular page

- src/components/ArabicaVersionTags.jsx
- src/components/BsrVersionTags.jsx
- src/components/MochaVersionTags.jsx
Resolves #877 
https://github.com/celestiaorg/docs/assets/46639943/ba32eb3b-8a0c-4a91-a721-7e0f31466f97
> docs: add Chain ID to network pages and network page

- versions/constants.js
Bumps to Rollkit v0.9.0 for Arabica (on [Arabica](https://docs.celestia.org/nodes/arabica-devnet/#software-version-numbers) page and [network](https://docs.celestia.org/nodes/participate/) page). Mocha still is not supported yet.
> deps: bump rollkit version

- docs/nodes/mocha-testnet.mdx
> Add kjnodes public endpoints to mocha testnet

- docs/nodes/mocha-testnet.mdx
> Add itrocket RPC, API, gRPC

- docs/nodes/mocha-testnet.mdx
> Add Endpoints Cumulo

- docs/nodes/mocha-testnet.mdx
> add polkachu endpoints for mocha testnet

- docs/nodes/mocha-testnet.mdx
> AviaOne add RPC API GRPC

- docs/nodes/mocha-testnet.mdx
Architect Nodes mocha-3 public end points.
> Added Architect Nodes end points

- docs/nodes/mocha-testnet.mdx
Add Mocha-3 endpoints by F5 Nodes
> Add Mocha-3 endpoints by F5 Nodes

- docs/nodes/mocha-testnet.mdx
> Added MMS team endpoints for mocha-3

- docs/developers/celestia-node-key.mdx
- docs/developers/node-api.md
- docs/developers/node-tutorial.mdx
- docs/nodes/celestia-node-metrics.md
- docs/nodes/celestia-node-troubleshooting.mdx
- docs/nodes/docker-images.mdx
- docs/nodes/light-node.mdx
- docs/nodes/mocha-testnet.mdx
> docs: remove deprecated gateway

- docs/developers/optimism-devnet.mdx
- docs/developers/overview.md
- docs/nodes/mocha-testnet.mdx
Bumps to https://github.com/celestiaorg/optimism/releases/tag/v0.1.1-OP_v1.0.6-CN_v0.11.0-rc6 and modifies tutorial with tabs
> docs: celopstia updates for new version

- docs/developers/keplr.mdx
- src/components/AddNetworkKeplr.jsx
Updates RPC for Keplr on Arabica.
> deps: update RPC for keplr

- docs/developers/node-tutorial.mdx
> docs: add `celestia rpc state Transfer` example

- docs/nodes/full-consensus-node.md
> Added note about full-consensus-node storage requirements

- docs/nodes/full-consensus-node.mdx
- docs/nodes/mocha-testnet.mdx
- docs/nodes/overview.md
> add arabica instructions for Full Consensus Node, resolves #912

- docs/developers/optimism-devnet.mdx
> update optimism version

- docs/developers/demos.md
- docs/developers/full-stack-modular-development-guide.md
- docs/developers/rollkit.md
- docs/nodes/itn-deploy-rollup.md
> [bug] resolve broken rollkit links

- docs/developers/optimism-devnet.mdx
To https://github.com/celestiaorg/optimism/releases/tag/v0.1.3-OP_v1.0.6-CN_v0.11.0-rc8
Resolves #939
> deps: bump celestiaorg/optimism version

- docs/developers/node-tutorial.mdx
> fix: match input/output on tutorial

- docs/nodes/instantiate-testnet.md
> docs: update instantiate-testnet.md guide

- docs/developers/keplr.mdx
resolves #940 
i also hid blockspace race to avoid confusion
> docs: add "how to create account" to keplr page

- docs/community/modular-meetup-toolkit.md
- docs/developers/celestia-node-key.mdx
- docs/developers/full-stack-modular-development-guide.md
- docs/developers/light-node-video.md
- docs/developers/node-tutorial.mdx
- docs/developers/prompt-scavenger.mdx
- docs/nodes/arabica-devnet.mdx
- docs/nodes/blockspace-race.mdx
- docs/nodes/bridge-node.mdx
- docs/nodes/celestia-node-metrics.md
- docs/nodes/config-toml.md
- docs/nodes/decide-node.md
- docs/nodes/docker-images.mdx
- docs/nodes/full-consensus-node.mdx
- docs/nodes/full-storage-node.mdx
- docs/nodes/itn-deploy-bridge.md
- docs/nodes/itn-deploy-light.md
- docs/nodes/itn-rpc-node.md
- docs/nodes/itn-setup-validator.md
- docs/nodes/itn-upgrade-node-bridge.md
- docs/nodes/light-node.mdx
- docs/nodes/overview.md
- docs/nodes/qgb-intro.md
- docs/nodes/quick-start.md
- docs/nodes/systemd.md
- docs/nodes/validator-node.md
All node types should be lower case in alignment with using sentence case in our documentation.
Resolves #160
> docs: standardize casing for node types

- docs/developers/overview.md
- docs/developers/wallets.md
- sidebars.js
Adds a wallets page for an overview of wallets on Celestia.
Resolves #959
> docs: add wallets.md page for overview

- .eslintrc.json
- docs/nodes/validator-node.mdx
> docs(): update chain-id from mocha to mocha-4

- docs/nodes/mocha-testnet.mdx
F5 Nodes endpoints added to Mocha testnet page in docs.
> docs: f5nodes endpoints added

- docs/nodes/mocha-testnet.mdx
> docs: update mocha endpoints to shortened URIs

- docs/developers/staking.md
- sidebars.js
Adds a page with staking interfaces for mocha testnet.
resolves #961
> docs: add staking page

- docs/nodes/mocha-testnet.mdx
> Brightlystake endpoints

- package.json
> fix: auto opening of browser on `yarn start`

- README.md
> Update README.md ReadMe duplicate #11

- docs/developers/build-modular.md
- docs/developers/celestia-app-vesting.md
- docs/developers/deploy-on-bubs.md
- docs/developers/full-stack-modular-development-guide.md
- docs/developers/ibc-relayer.md
- docs/developers/intro-to-op-stack.md
- docs/developers/node-api.md
- docs/developers/node-tutorial.mdx
- docs/developers/optimism-devnet.mdx
- docs/developers/prompt-scavenger.mdx
- docs/developers/staking.md
- docs/developers/submit-data.md
- docs/learn/data-availability-faq.md
- docs/nodes/celestia-app-commands.md
> docs: fix typos

- src/pages/arabica-9.mdx
> chore: bump to v0.11.0-rc9.1 for celestia-node for arabica-9

- .github/workflows/latest_tags.yml
> update latest-tag workflow to use new PAT

- docs/nodes/qgb-deploy.md
- docs/nodes/qgb-keys.md
- docs/nodes/qgb-orchestrator.md
- docs/nodes/qgb-relayer.md
Resolves #1111 
Finishes off #1073
> chore: update qgb

- docs/nodes/consensus-node.mdx
- docs/nodes/instantiate-testnet.md
> chore: Core/App Doc Updates

- docs/developers/node-tutorial.mdx
Fixes a typo of "the the" and removes an extra "the"
> chore: fix typo

- docs/developers/node-tutorial.mdx
- docs/developers/submit-data.md
> chore: remove extra "rpc" subcmds

- docs/developers/blobstream-offchain.md
> docs: add links to blobstream related  RPC endpoints

- docs/developers/integrate-celestia.md
- sidebars.js
> docs: integrate celestia -> + service providers

- docs/developers/blobstream-offchain.md
> docs: add details on how to use the core blobstream proofs endpoint

- docs/nodes/celestia-node-metrics.md
Adds context on the `--metrics.tls` flag, and the differences in setting this value to `false` versus `true`
> docs: add context to metrics doc for TLS flag

- .vitepress/config.ts
Resolves a similar issue to https://github.com/rollkit/docs/pull/245.
> fix: favicon (turn off dark mode favicon)

- nodes/participate.md
> fix: missing testnet link

- .github/workflows/deploy.yml
I noticed that old versions of pages are still accessible, due to old deployment not being orphaned with new workflow
https://docs.celestia.org/developers/node-tutorial/ as example
versus https://docs.celestia.org/developers/node-tutorial
> feat: force_orphan true

- developers/submit-data.md
Resolves #1173 by reducing some of the variables to acronyms, and describing them in plain text below
> fix: long latex equations

- package.json
- yarn.lock
> chore: upgrade vitepress version

- .vitepress/config.ts
This PR turns on the [vitepress sitemap generation](https://vitepress.dev/guide/sitemap-generation#sitemap-generation), to allow feeding sitemap into chatbase bot (celestia GPT) easier.
> feat: add sitemap

- .vitepress/config.ts
- developers/rollup-overview.md
> feat: add astria to rollup category and page

- nodes/consensus-node.md
adds some docs for pruning and storage options/reccomendations. I have taken the time to experiement with all of these option combonations so I think we should expect to continually update these. Opening for review now, but will try to revisit this today/tmrw
> docs: initial storage docs

- developers/optimism-devnet.md
> fix: missing closing code-group

- .vitepress/config.ts
- nodes/systemd.md
- nodes/transaction-resubmission.md
Resolves #1092, documenting transaction resubmission guidelines.
> chore: add transaction resubmission document to nodes/resources section

- developers/blobstream-offchain.md
Minor grammar fixes in blobstream docs
> Minor fixes on blobstream docs

- nodes/mocha-testnet.md
> Add TestnetPride archive node (RPC, gRPC, API) to mocha-testnet.md

- learn/tia.md
> chore: add docs on denominations

- nodes/consensus-node.md
- nodes/transaction-resubmission.md
> fix: example file locations, typos

- nodes/consensus-node.md
changes the sub section from Bridge Node since that is confusing
> fix: clarify bridge node section name

- .vitepress/config.ts
- nodes/consensus-node.md
> feat: add deep outline

- nodes/mocha-testnet.md
> fix: remove mocha explorer that is set up for mainnet

- nodes/consensus-node.md
[Preview of consensus node page](https://docs.celestia.org/pr-preview/pr-1219/nodes/consensus-node#storage-and-pruning-configurations)
> fix: validator updates

- developers/node-tutorial.md
- nodes/light-node.md
> bug: replace rpc url

- nodes/mainnet.md
> chore: update order of explorers

- developers/node-api.md
The link in the documentation was broken, so I fixed it.
> Edit broken link

- .vitepress/config.ts
This PR adds a link to known relayers on mintscan.
> chore: add link to ibc relayers on mintscan

- nodes/mainnet.md
> Add Mainnet Endpoints by NodeStake

- nodes/consensus-node.md
This clarifies that blobstream will soon be available on Mocha, but is not yet live.
> chore: update consensus-node for blobstream

- nodes/celestia-node-metrics.md
> chore: add metrics example

- community/itn-tos.md
- developers/how-to-stake-tia.md
> chore: add itn-tos

- nodes/mainnet.md
> Adding Spidey Validator Public Endpoints for RPC, gRPC and API

- nodes/mainnet.md
Adding ContributionDAO RPC/API/GRPC endpoint
> Adding ContributionDAO RPC/API/GRPC endpoint

- nodes/celestia-app.md
This improves the UX for use of the `celestia-app.sh` script, with a suggestion from @ramin. This eliminates the need for the user to download the script.
> feat: improve celestia-app.sh script use

- .vitepress/config.ts
- community/itn-tos.md
> chore: add itn-tos to menu

- learn/tia.md
This clarifies the conversion on the TIA page, because in the current version it is not clear if it is "1 uTIA -> TIA" or "1 TIA -> uTIA"
> fix: clarify conversion

- nodes/mainnet.md
> chore: fix link

- nodes/mainnet.md
We add our gRPC, Tendermint JSON-RPC and REST services to the docs
> add stakin.com endpoints

- nodes/mainnet.md
> Add Cumulo Endpoints

- developers/celestia-node-key.md
- nodes/full-storage-node.md
> chore: remove old mdx links

- nodes/mainnet.md
> add mzonder mainnet RPCs

- .vitepress/config.ts
- developers/full-stack-modular-development-guide.md
- developers/intro-to-op-stack.md
- developers/optimism.md
- developers/rollup-overview.md
- learn/tia.md
- nodes/celestia-node-troubleshooting.md
- nodes/docker-images.md
also some linting that was auto applied
> chore: missing testnet->devnet instances in op guide

- developers/optimism-devnet.md
> chore: typo, capitalize O

- nodes/mainnet.md
> chore: add back numia

- nodes/blobstream-deploy.md
- nodes/blobstream-orchestrator.md
- nodes/blobstream-relayer.md
using `yarn import-blobstream` and based on https://github.com/celestiaorg/orchestrator-relayer/pull/585
> chore: update blobstream docs

- .vitepress/constants/constants.js
> chore: use proper blobstream version

- developers/optimism.md
Improves the visual diff of code block, similarly to this pr https://github.com/rollkit/docs/pull/274
> chore: improve example for light node on op

- developers/staking.md
> docs: outdated staking page

- .vitepress/constants/constants.js
> docs: update blobstream

- .vitepress/constants/constants.js
> chore: bump the orchestrator-relayer version

- .vitepress/components/OrchRelayerVersion.vue
- .vitepress/constants/constants.js
- nodes/blobstream-binary.md
- nodes/blobstream-orchestrator.md
> feat: add version of orch relayer link in docs, update version

- developers/rollkit.md
This PR updates a "Coming soon" link to the Polaris EVM tutorial on Rollkit.
> chore: add link to polaris

- .vitepress/config.ts
- developers/build-modular.md
- developers/rollup-overview.md
This changes the branch linked in the docs from "main" to "stable", which [are the same branch](https://github.com/Sovereign-Labs/sovereign-sdk/tree/stable/examples/demo-rollup#readme). The name has just changed.
Note: there is also a ["nightly" branch](https://github.com/Sovereign-Labs/sovereign-sdk/tree/nightly/examples/demo-rollup) of the repo.
> chore: update branch to stable for sov-sdk

- .vitepress/config.ts
- developers/celestia-app-wallet.md
- developers/optimism.md
Uses the polaris full stack guide in place of the former tutorial, which is outdated and uses ethermint and a janky ipfs component
Resolves #1120
> chore: use polaris tutorial for full stack guide

- .vitepress/config.ts
- nodes/blobstream-binary.md
- nodes/blobstream-deploy.md
> feat: add hardware requirements

- .vitepress/config.ts
- developers/eth-fallback.md
https://celestiaorg.github.io/docs/pr-preview/pr-1286/developers/eth-fallback
> feat: add eth fallback doc

- developers/blobstream.md
This PR adds new contract address for Blobstream on Arbitrum Sepolia and updates the contract address for Sepolia. It also adds a table for readability, making better use of the space (showing contract address).
[PREVIEW LINK](https://celestiaorg.github.io/docs/pr-preview/pr-1293/developers/blobstream#deployed-contracts)
Before:
After:
> feat: add arbitrum sepolia address and table

- nodes/mainnet.md
> added new section for analytics dashboards and added smart stake analytics

- community/modular-fellows.md
- developers/blobstream-proof-queries.md
- developers/ethereum-fallback.md
- developers/ibc-relayer.md
- learn/tia.md
- nodes/blobstream-bootstrapper.md
- nodes/celestia-app-commands.md
- nodes/instantiate-testnet.md
> Fix several typos

- nodes/mainnet.md
> Add Avril14th rpc/grpc endpoints

- nodes/consensus-node.md
> docs: update wrong register command for blobstream

- developers/staking.md
- nodes/mainnet.md
> add endpoints, add dashboard

- developers/ethereum-fallback.md
- developers/optimism-devnet.md
- nodes/mainnet.md
Fixes an outdated link to Ethereum fallback document.
> fix: link to ethereum fallback

- nodes/mainnet.md
This adds a bootstrapper dashboard to the mainnet page, mirroring https://github.com/celestiaorg/networks/pull/530
> feat: add bootstrapper dashboard 

- community/modular-meetup-intro.md
> feat: update modular meetup page

- .vitepress/config.ts
- nodes/celestia-app-upgrade-monitor.md
Closes https://github.com/celestiaorg/docs/issues/1326
The docs page added in this PR is mostly a placeholder so that please can discover the upgrade-monitor repo.
> feat: link to upgrade monitor README

- developers/node-tutorial.md
- nodes/celestia-node.md
Implementing suggestions from code review after merge:
https://github.com/celestiaorg/docs/pull/1321#discussion_r1427418276 https://github.com/celestiaorg/docs/pull/1321#discussion_r1427419065
> fix: node v0.12.1 build details

- nodes/mainnet.md
Closes https://github.com/celestiaorg/devops/issues/703
> feat: consensus endpoints before DA endpoints

- nodes/mocha-testnet.md
> Adding Spidey Mocha-4 endpoints

- .vitepress/components/AddNetworkKeplr.vue
- developers/keplr.md
Updates min gas fees, mirroring update in network.
> feat: update min gas fees for keplr example

- nodes/mainnet.md
> Adding easy2stake public rpc endpoints

- developers/optimism-devnet.md
Upgrades Optimism devnet version to v1.0.0-OP_op-node/v1.4.0-CN_v0.12.1 and adds section on span batches.
> feat: update OP to v1.0.0-OP_op-node/v1.4.0-CN_v0.12.1

- nodes/mainnet.md
> feat: add network parameters and description of max bytes

- developers/node-tutorial.md
- nodes/celestia-node.md
Jemalloc requires a higher version of Go than our docs use. This adds a note about that
> feat: add note about go version

- developers/submit-data.md
A few nits I correct while re-reading this page.
> docs: update submit data

- developers/optimism.md
> feat: update celestia-da

- developers/node-tutorial.md
Adds a guide for submitting a blob with curl to the node tutorial.
Resolves #1342
> feat: add curl guide to node-tutorial.md

- developers/optimism-devnet.md
- developers/optimism.md
> feat: version bump celestia-da to v0.12.9 and op stack version compat with v0.12.9

- nodes/arabica-devnet.md
Added Arabica explorer url by Celenium.
- [+] New and updated code has appropriate documentation
- [+] New and updated code has new and/or updated testing
- [+] Required CI checks are passing
- [+] Visual proof for any user facing features like CLI or documentation updates
- [+] Linked issues closed with keywords
> Update arabica-devnet with celenium explorer url

- developers/blobstream.md
> docs: update blobstream contract addresses

- developers/blobstream.md
Update old docs for deployed contracts
> docs: remove invalid testnet from blobstream deployed contracts

- nodes/mocha-testnet.md
> docs: remove deprecated rpc endpoints

- developers/celestia-node-key.md
Resolves https://github.com/celestiaorg/docs/issues/1602
> docs: remove old flag

- developers/celestia-node-key.md
- developers/feegrant-for-blobs.md
- developers/node-tutorial.md
- nodes/bridge-node.md
- nodes/full-storage-node.md
- nodes/light-node.md
Flagged in [Discord message](https://discord.com/channels/638338779505229824/804370245778276374/1272858295828221953), `--keyring.accname` has changed to `--keyring.keyname`
> docs: keyring.accname -> keyring.keyname

- .vitepress/config.ts
- developers/blobstream-contracts.md
- developers/blobstream-offchain.md
- developers/blobstream-proof-queries.md
- developers/blobstream.md
- developers/blobstreamx.md
> docs: update to SP1 docs

- developers/blobstream-proof-queries.md
> docs: resolve 1487

- developers/transaction-resubmission.md
> docs: add HA provider note

- nodes/hardfork-process.md
> docs: change heading to "lemongrass network upgrade"

- .vitepress/constants/mainnet_versions.js
> chore: bump app and node versions for mainnet

- how-to-guides/mocha-testnet.md
> docs: fix dead link

- how-to-guides/nodes-overview.md
> docs: update storage reqs/add archival da

- how-to-guides/quick-start.md
- tutorials/celestia-node-key.md
Still refining this implementation, but would appreciate any early feedback on the approach or potential improvements
> feat: add more cel-key docs

- how-to-guides/celestia-app.md
> docs: add next steps to celestia-app page

- how-to-guides/quick-start.md
previous is not wotking on site
> docs: change path to mocha-testnet.md

- how-to-guides/quick-start.md
- learn/how-celestia-works/data-availability-layer.md
nothing fancy just fixed some typos.
> chore: fix typos in docs

- .vitepress/constants/mainnet_versions.js
> mainnet: bump versions

- how-to-guides/blobstream-offchain.md
- how-to-guides/blobstream-proof-queries.md
- how-to-guides/blobstream-rollups.md
- how-to-guides/celestia-app-slashing.md
- tutorials/golang-client-tutorial.md
- tutorials/node-tutorial.md
- tutorials/rust-client-tutorial.md
Closes https://github.com/celestiaorg/docs/issues/2190
link-check passed: https://github.com/celestiaorg/docs/actions/runs/16808831887/job/47608483817?pr=2191
> fix: celestia-app spec links

- .vitepress/constants/arabica_versions.js
> docs: update arabica

- .vitepress/constants/mocha_versions.js
> docs: v5.0.2-mocha

- how-to-guides/mainnet.md
> add deNodes endpoints

- .vitepress/constants/mocha_versions.js
> chore: update new mocha v0.27.4-mocha
